# Generated by Django 4.2.7 on 2023-12-09 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signup", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
